# Sample workflow for building and deploying a Hugo site to Azure Spring Apps
name: Deploy Hugo site to Azure Spring Apps

on:
  # Runs on pushes targeting the default branch, i.e. main
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set environment variables
env:
  SPRING_APPS_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: d611a8ae-45e6-4f08-8353-572e149ff4c7
  BASE_URL: "https://azurespringapps.com"
  ASA_NAME: "production"
  APP_NAME: "blog"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "azure-spring-apps"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash


jobs:

  # Build job
  build:
    name: Deploy Hugo website to Azure Spring App instance
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.111.3
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ env.BASE_URL }}/"
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to production step with source code
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: deploy
          service-name: ${{ env.ASA_NAME }}
          app-name: ${{ env.APP_NAME }}
          package: ${{ env.SPRING_APPS_PATH }}
          build-env: "-BP_WEB_SERVER nginx"
          use-staging-deployment: false
